# Generated by Django 3.0.7 on 2020-06-14 15:11

import django.contrib.auth.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(editable=False, max_length=64, unique=True)),
                ('red_score', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('black_score', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('finished_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.CharField(max_length=128)),
                ('uci', models.CharField(max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiangqi.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiangqi.Player')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_set', to='xiangqi.Game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='black_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='xiangqi.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='red_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='xiangqi.Player'),
        ),
        migrations.CreateModel(
            name='DrawEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('xiangqi.gameevent',),
        ),
        migrations.AddIndex(
            model_name='gameevent',
            index=models.Index(fields=['name', 'created_at'], name='xiangqi_gam_name_96cf19_idx'),
        ),
    ]
