# Generated by Django 2.2 on 2019-04-06 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('player_limit', models.PositiveIntegerField(default=2)),
                ('board_dimensions', models.CharField(max_length=128)),
                ('move_time_limit', models.CharField(max_length=128, null=True)),
                ('game_time_limit', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('starting_position', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiangqi.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiangqi.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('notation', models.CharField(max_length=32)),
                ('from_position', models.CharField(max_length=32, null=True)),
                ('to_position', models.CharField(max_length=32)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiangqi.Game')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiangqi.Participant')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiangqi.Piece')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiangqi.MoveType')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='xiangqi.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='participants',
            field=models.ManyToManyField(through='xiangqi.Participant', to='xiangqi.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xiangqi.Result'),
        ),
    ]
