# Generated by Django 2.2 on 2019-06-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='role',
            field=models.CharField(default='x', max_length=32),
            preserve_default=False,
        ),
    ]
