# Generated by Django 2.2 on 2019-06-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='code',
            field=models.CharField(default='x', max_length=1, unique=True),
            preserve_default=False,
        ),
    ]
