# Generated by Django 2.2 on 2020-05-07 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0002_auto_20200405_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refreshtoken',
            name='player',
        ),
        migrations.DeleteModel(
            name='AccessToken',
        ),
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
