# Generated by Django 2.2 on 2019-11-29 18:04

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    """
    Unset notation and move type for all moves
    """
    Move = apps.get_model('xiangqi', 'Move')
    Move.objects.update(notation=None, type=None)


class Migration(migrations.Migration):

    dependencies = [('xiangqi', '0003_remove_move_piece')]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='notation',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='type',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='xiangqi.MoveType',
            ),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
