# Generated by Django 3.0.7 on 2020-06-17 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0003_takebackevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='red_player',
            new_name='player1',
        ),
    ]
