# Generated by Django 2.2 on 2019-06-22 02:03

from django.db import migrations, models
import django.db.models.deletion
import xiangqi.models


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0003_piece_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(db_index=True)),
                ('file', models.PositiveIntegerField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='color',
            field=models.CharField(choices=[(xiangqi.models.Color('red'), 'red'), (xiangqi.models.Color('black'), 'black')], default='no color', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='move',
            name='from_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xiangqi.Position'),
        ),
        migrations.AlterField(
            model_name='move',
            name='to_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xiangqi.Position'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='starting_position',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xiangqi.Position'),
            preserve_default=False,
        ),
    ]
