# Generated by Django 2.2 on 2020-05-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0004_remove_game_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameTransition',
        ),
    ]
