# Generated by Django 2.2 on 2019-06-22 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0004_auto_20190622_0203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='to_position',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='move',
            old_name='from_position',
            new_name='origin',
        ),
        migrations.RenameField(
            model_name='piece',
            old_name='starting_position',
            new_name='origin',
        ),
    ]
