# Generated by Django 2.2 on 2019-11-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0004_auto_20191129_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='type',
        ),
        migrations.DeleteModel(
            name='MoveType',
        ),
    ]
