# Generated by Django 3.0.7 on 2020-06-17 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0004_auto_20200617_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='black_player',
            new_name='player2',
        ),
    ]
