# Generated by Django 3.0.7 on 2020-06-17 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0005_auto_20200617_0426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='red_score',
            new_name='score1',
        ),
    ]
