# Generated by Django 2.2 on 2019-06-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0005_auto_20190622_0424'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('rank', 'file')},
        ),
    ]
