# Generated by Django 2.2 on 2020-05-12 20:52

from django.db import migrations, models

from xiangqi.lib.pyffish import xiangqi


def backfill(apps, schema_editor):
    Game = apps.get_model("xiangqi", "Game")
    games = Game.objects.prefetch_related("move_set")

    for game in games:
        for move in game.move_set.all():
            previous_fen = (
                move.previous_move.fen if move.previous_move else xiangqi.start_fen()
            )
            move.fen = xiangqi.get_fen(previous_fen, [move.name])
            move.save()


class Migration(migrations.Migration):

    dependencies = [("xiangqi", "0006_move_previous_move")]

    operations = [
        migrations.AddField(
            model_name="move",
            name="fen",
            field=models.CharField(default="x", max_length=128),
            preserve_default=False,
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
