# Generated by Django 2.2 on 2019-12-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0006_accesstoken_refreshtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
