# Generated by Django 3.0.7 on 2020-06-17 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0006_auto_20200617_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='black_score',
            new_name='score2',
        ),
    ]
