# Generated by Django 2.2 on 2020-05-12 20:52

from itertools import chain
from types import SimpleNamespace

from django.db import migrations, models

from lib.pyffish import xiangqi


def backfill(apps, schema_editor):
    Game = apps.get_model("xiangqi", "Game")
    games = Game.objects.prefetch_related("move_set")

    for game in games:
        starting_position = SimpleNamespace(pk=0, fen=xiangqi.start_fen())
        sorted_moves = sorted(
            chain([starting_position], game.move_set.all()), key=lambda obj: obj.pk
        )

        for previous_move, move in zip(sorted_moves, sorted_moves[1:]):
            move.fen = xiangqi.get_fen(previous_move.fen, [move.fan])
            move.save()


class Migration(migrations.Migration):

    dependencies = [("xiangqi", "0006_auto_20200517_1536")]

    operations = [
        migrations.AddField(
            model_name="move",
            name="fen",
            field=models.CharField(default="x", max_length=128),
            preserve_default=False,
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
