# Generated by Django 2.2.10 on 2020-05-24 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0007_move_fen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='fan',
            new_name='uci',
        ),
    ]
