# Generated by Django 2.2 on 2020-02-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0007_delete_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
