# Generated by Django 2.2 on 2019-06-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0007_auto_20190623_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.PositiveIntegerField(default=1500),
        ),
    ]
