# Generated by Django 2.2 on 2019-06-23 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0008_auto_20190623_0522'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('game', 'color')},
        ),
        migrations.RemoveField(
            model_name='participant',
            name='role',
        ),
    ]
