# Generated by Django 3.0.7 on 2020-06-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0008_gamerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerequest',
            name='player',
        ),
        migrations.AddField(
            model_name='gamerequest',
            name='players',
            field=models.ManyToManyField(to='xiangqi.Player'),
        ),
    ]
