# Generated by Django 2.2 on 2020-05-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0008_move_fen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='previous_move',
        ),
    ]
