# Generated by Django 2.2 on 2020-02-13 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0008_move_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xiangqi.Position'),
        ),
    ]
