# Generated by Django 2.2.10 on 2020-06-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0008_auto_20200524_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='game',
            name='finished_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='red_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
