# Generated by Django 3.0.7 on 2020-06-29 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0008_gamerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerequest',
            name='closed_at',
        ),
        migrations.AlterField(
            model_name='gamerequest',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='xiangqi.Player'),
        ),
    ]
