# Generated by Django 2.2 on 2020-02-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0009_auto_20200213_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='move',
            name='notation',
        ),
        migrations.RemoveField(
            model_name='move',
            name='origin',
        ),
        migrations.AlterField(
            model_name='move',
            name='name',
            field=models.CharField(default='x1x1', max_length=10),
            preserve_default=False,
        ),
    ]
