# Generated by Django 2.2 on 2019-06-23 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0009_auto_20190623_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xiangqi.Player'),
        ),
    ]
