# Generated by Django 2.2.10 on 2020-06-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0009_auto_20200603_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
