# Generated by Django 3.0.7 on 2020-06-29 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0009_auto_20200629_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamerequest',
            old_name='players',
            new_name='player_set',
        ),
    ]
