# Generated by Django 2.2 on 2019-06-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0010_auto_20190623_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='xid',
            field=models.CharField(default='x', editable=False, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
