# Generated by Django 2.2.10 on 2020-06-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0010_auto_20200603_2340'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gameevent',
            index=models.Index(fields=['name', 'created_at'], name='xiangqi_gam_name_96cf19_idx'),
        ),
    ]
