# Generated by Django 2.2 on 2020-02-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0010_auto_20200215_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='order',
        ),
    ]
