# Generated by Django 2.2.10 on 2020-06-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0010_auto_20200603_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
