# Generated by Django 3.0.7 on 2020-06-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0010_auto_20200629_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerequest',
            name='player_set',
            field=models.ManyToManyField(related_name='game_request_set', to='xiangqi.Player'),
        ),
    ]
