# Generated by Django 2.2 on 2020-03-28 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0011_remove_move_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='move',
            options={'ordering': ['pk']},
        ),
        migrations.DeleteModel(
            name='Piece',
        ),
    ]
