# Generated by Django 2.2 on 2019-06-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0011_game_xid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='xid',
            new_name='slug',
        ),
    ]
