# Generated by Django 2.2 on 2019-06-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0012_auto_20190623_0738'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('game', 'color'), ('game', 'player')},
        ),
    ]
