# Generated by Django 2.2 on 2020-03-28 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0012_auto_20200328_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='board_dimensions',
        ),
        migrations.RemoveField(
            model_name='game',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='game',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_time_limit',
        ),
        migrations.RemoveField(
            model_name='game',
            name='move_time_limit',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_limit',
        ),
        migrations.RemoveField(
            model_name='game',
            name='result',
        ),
        migrations.RemoveField(
            model_name='game',
            name='start_time',
        ),
    ]
