# Generated by Django 2.2 on 2019-06-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0013_auto_20190623_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='name',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='piece',
            unique_together={('name', 'origin')},
        ),
    ]
