# Generated by Django 3.0.7 on 2020-06-29 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0013_auto_20200629_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerequest',
            name='player',
        ),
        migrations.AddField(
            model_name='gamerequest',
            name='player1',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='xiangqi.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamerequest',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='xiangqi.Player'),
        ),
    ]
