# Generated by Django 2.2 on 2020-03-28 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0014_delete_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
    ]
