# Generated by Django 2.2 on 2019-06-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0015_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='expires_in',
        ),
        migrations.AddField(
            model_name='token',
            name='expires_on',
            field=models.PositiveIntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
