# Generated by Django 2.2 on 2020-03-29 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0016_gameevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameevent',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_set', to='xiangqi.Game'),
        ),
    ]
