# Generated by Django 2.2 on 2020-03-29 14:23

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0017_auto_20200329_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='state',
            field=django_fsm.FSMField(default='new', max_length=50),
        ),
    ]
