# Generated by Django 2.2 on 2020-03-29 14:58

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0018_game_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state',
            field=django_fsm.FSMField(default='new', max_length=50, protected=True),
        ),
    ]
