# Generated by Django 2.2 on 2020-03-29 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0020_auto_20200329_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('to_state', models.CharField(max_length=50)),
                ('casual_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_set', to='xiangqi.GameEvent')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiangqi.Game')),
            ],
        ),
    ]
