# Generated by Django 2.2 on 2020-03-29 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0021_gametransition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametransition',
            name='casual_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transition_set', to='xiangqi.GameEvent'),
        ),
    ]
