# Generated by Django 2.2 on 2020-03-29 20:05

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0022_auto_20200329_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state',
            field=django_fsm.FSMField(default='red_turn', max_length=50),
        ),
    ]
