# Generated by Django 2.2 on 2020-03-29 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0023_auto_20200329_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametransition',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_set', to='xiangqi.Game'),
        ),
    ]
