# Generated by Django 2.2 on 2020-03-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0026_remove_game_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='participant',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
