# Generated by Django 2.2 on 2020-03-31 17:13

from django.db import migrations, models
import django.db.models.deletion
import xiangqi.models.color


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0027_auto_20200331_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xiangqi.User'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(choices=[(xiangqi.models.color.Color('red'), 'red'), (xiangqi.models.color.Color('black'), 'black')], max_length=32)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiangqi.Game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xiangqi.Player')),
            ],
            options={
                'unique_together': {('game', 'player'), ('game', 'color')},
            },
        ),
    ]
