# Generated by Django 2.2 on 2020-04-03 03:55

from django.db import migrations


def recreate_game(apps, schema_editor):
    Game = apps.get_model("xiangqi", "Game")
    User = apps.get_model("auth", "User")

    red_player = User.objects.get(username="bycepto")
    black_player = User.objects.get(username="jkalltheway")
    Game.objects.filter(slug="ABC123").update(
        red_player=red_player, black_player=black_player
    )


class Migration(migrations.Migration):

    dependencies = [("xiangqi", "0028_auto_20200331_1713")]

    operations = [migrations.RunPython(recreate_game, migrations.RunPython.noop)]
