# Generated by Django 2.2 on 2020-04-03 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqi', '0029_auto_20200403_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
